import { ALL_PERMISSIONS_OFF } from './allPermissionsOff.constant'
import type { UserPermissions } from './userPermissions.interface'

export const ROLE_PERMISSION_FALLBACKS: Record<string, UserPermissions> = {
  admin: Object.fromEntries(Object.keys(ALL_PERMISSIONS_OFF).map((key) => [key, true])) as unknown as UserPermissions,
  developer: {
    ...ALL_PERMISSIONS_OFF,
    servers_view: true,
    servers_create: true,
    servers_edit_settings: true,
    servers_manage_connection: true,
    servers_toggle_active: true,
    servers_share: true,
    tools_view: true,
    tools_create: true,
    tools_edit: true,
    tools_delete: true,
    tools_test: true,
    endpoints_create: true,
    resources_view: true,
    resources_create: true,
    resources_edit: true,
    resources_delete: true,
    prompts_view: true,
    prompts_create: true,
    prompts_edit: true,
    prompts_delete: true,
    secrets_view_names: true,
    api_keys_view: true,
    api_keys_create: true,
    api_keys_delete: true,
    audit_view: true,
    templates_use: true,
    ai_providers_view: true,
    ai_providers_create: true,
    ai_providers_edit: true,
    ai_providers_delete: true,
    ai_providers_execute: true,
    observability_view: true,
    error_tracking_view: true,
    error_tracking_create: true,
    error_tracking_edit: true,
    error_tracking_delete: true,
  },
  editor: {
    ...ALL_PERMISSIONS_OFF,
    servers_view: true,
    servers_share: true,
    tools_view: true,
    tools_create: true,
    tools_edit: true,
    tools_test: true,
    endpoints_create: true,
    resources_view: true,
    resources_create: true,
    resources_edit: true,
    prompts_view: true,
    prompts_create: true,
    prompts_edit: true,
    secrets_view_names: true,
    api_keys_view: true,
    templates_use: true,
    ai_providers_view: true,
    ai_providers_create: true,
    ai_providers_edit: true,
    ai_providers_execute: true,
    observability_view: true,
    error_tracking_view: true,
    error_tracking_create: true,
    error_tracking_edit: true,
  },
  viewer: {
    ...ALL_PERMISSIONS_OFF,
    servers_view: true,
    tools_view: true,
    resources_view: true,
    prompts_view: true,
  },
}
